In [ ]:
#problem1
import numpy as np

# 1. Initialize an empty array with size 2x2 using np.zeros (more predictable than np.empty)
empty_array = np.zeros((2, 2))
print(empty_array)

# 2. Initialize an all-one array with size 4x2 using np.ones and dtype float
ones_array = np.ones((4, 2))
print(ones_array)

# 3. Create a filled array using broadcasting from np.full_like
template = np.array([[0, 0], [0, 0]])
filled_array = np.full_like(template, fill_value=9)
print(filled_array)

# 4. Use np.shape and np.dtype manually with np.zeros
zeros_like_array = np.zeros(np.shape(template), dtype=template.dtype)
print(zeros_like_array)

# 5. Use np.ones with shape and dtype extracted from another array
ones_like_array = np.ones(template.shape, dtype=template.dtype)
print(ones_like_array)

# 6. Convert list to array and reshape to column vector
new_list = [1, 2, 3, 4]
converted_array = np.array(new_list).reshape(-1, 1)
print(converted_array)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[9 9]
 [9 9]]
[[0 0]
 [0 0]]
[[1 1]
 [1 1]]
[[1]
 [2]
 [3]
 [4]]


In [ ]:
#problem2

import numpy as np

# 1. Array with values from 10 to 49
array1 = np.arange(10, 50)
print(array1)

# 2. 3x3 matrix with values from 0 to 8
matrix = np.arange(9).reshape(3, 3)
print(matrix)

# 3. 3x3 identity matrix
identity_matrix = np.eye(3)
print(identity_matrix)

# 4. Random array of size 30 and its mean
random_array = np.random.random(30)
mean_value = random_array_30.mean()
print(random_array)
print(mean_value)

# 5. 10x10 random array and its min/max
random_matrix = np.random.random((10, 10))
min_value = random_matrix_10x10.min()
max_value = random_matrix_10x10.max()
print(random_matrix)
print(min_value)
print(max_value)

# 6. Zero array of size 10 with 5th element replaced by 1
zero_array = np.zeros(10)
zero_array[4] = 1
print(zero_array)

# 7. Reverse array
arr = [1, 2, 0, 0, 4, 0]
reversed_arr = arr[::-1]
print(reversed_arr)

# 8. 2D array with 1 on border and 0 inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print(border_array)

# 9. 8x8 checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0.78210191 0.96358433 0.73100226 0.67314658 0.88414261 0.0493267
 0.10875114 0.81073416 0.76386858 0.23223372 0.68564149 0.37970856
 0.00534643 0.52951477 0.69225259 0.46527225 0.3592771  0.83182028
 0.42954193 0.31034295 0.3903177  0.7869693  0.85090744 0.98637126
 0.84636431 0.48098264 0.81270009 0.1658591  0.37115675 0.71694163]
0.4263460998109881
[[0.34558701 0.95082224 0.20831196 0.44213153 0.61261649 0.81883619
  0.39754026 0.55749279 0.34689324 0.78259625]
 [0.21444477 0.310079   0.98854518 0.34898386 0.19279627 0.2387681
  0.73550248 0.26826367 0.99238227 0.47967224]
 [0.01450414 0.2712752  0.72529683 0.89890898 0.71674085 0.23664326
  0.10529018 0.38357855 0.64685786 0.4869073 ]
 [0.52432886 0.12410756 0.16924854 0.47745475 0.31064092 0.71700769
  0.0280581  0.6910545  0.01473083 0.87227127]

In [ ]:
#problem3
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays
add = x + y
print(add)

# 2. Subtract the two arrays
sub = x - y
print(sub)

# 3. Multiply the array with any integer (e.g., 3)
mul = x * 3
print(mul)

# 4. Square of each element in array x
square = x ** 2
print(square)

# 5. Dot products
dot_vw = np.dot(v, w)       # v and w are 1D
dot_xv = np.dot(x, v)       # x is 2x2, v is 1D
dot_xy = np.dot(x, y)       # x and y are 2x2
print(dot_vw)
print(dot_xv)
print(dot_xy)

# 6. Concatenate x and y along rows; v and w along columns
concat_xy_row = np.concatenate((x, y), axis=0)
concat_vw_col = np.column_stack((v, w))
print(concat_xy_row)
print(concat_vw_col)

# 7. Concatenate x and v — this will raise an error due to shape mismatch
try:
    concat_xv = np.concatenate((x, v), axis=0)
except ValueError as e:
    concat_xv_error = str(e)
    print(concat_xv_error)


[[ 6  8]
 [10 13]]
[[-4 -4]
 [-4 -3]]
[[ 3  6]
 [ 9 15]]
[[ 1  4]
 [ 9 25]]
219
[29 77]
[[19 22]
 [50 58]]
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 11]
 [10 12]]
all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [ ]:
#problem4

import numpy as np

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])
##1
A_inv = np.linalg.inv(A)
identity_check = np.dot(A, A_inv)
print (identity_check)

##2
AB = np.dot(A, B)
BA = np.dot(B, A)
print( AB)
print( BA)

##3
AB_T = AB.T
BT_AT = np.dot(B.T, A.T)
print(AB_T)
print(BT_AT)


##linear equation

# Coefficient matrix A and RHS vector B
A_sys = np.array([[2, -3, 1],
                  [1, -1, 2],
                  [3,  1, -1]])
B_sys = np.array([-1, -3, 9])

# Solve using inverse
A_sys_inv = np.linalg.inv(A_sys)
X = np.dot(A_sys_inv, B_sys)
print (X)



[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
[[23 13]
 [51 29]]
[[36 44]
 [13 16]]
